### ISSUE TITLE
Global tag is not allowed

### ISSUE THREAD

**Issue by tianxie** [copper-engine/copper-engine#119]
After upgraded from 5.4.2 to 5.5.2, I encounted this error:

```
[2024-07-11 15:17:08.971][P#DEFAULT#DBReader][ERROR][tid:][o.copperengine.core.persistent.AbstractSqlDialect#264][decoding of '341588c8-3fda-4e0a-b965-620bc9ed5eae' failed: Global tag is not allowed: tag:yaml.org,2002:com.example.workflow.data.WorkflowInputData
 in 'string', line 1, column 1:
    !!com.example.workflow.d ... 
    ^
]
org.yaml.snakeyaml.composer.ComposerException: Global tag is not allowed: tag:yaml.org,2002:com.example.workflow.data.WorkflowInputData
 in 'string', line 1, column 1:
    !!com.example.workflow.d ... 
    ^

	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:304)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:422)
	at org.copperengine.ext.persistent.YamlSerializer.deserializeData(YamlSerializer.java:65)
	at org.copperengine.core.persistent.StandardJavaSerializer.deserializeWorkflow(StandardJavaSerializer.java:156)
	at org.copperengine.core.persistent.AbstractSqlDialect.dequeue(AbstractSqlDialect.java:256)
	at org.copperengine.core.persistent.ScottyDBStorage$4.run(ScottyDBStorage.java:182)
	at org.copperengine.core.persistent.ScottyDBStorage$4.run(ScottyDBStorage.java:179)
	at org.copperengine.core.persistent.txn.CopperTransactionController$1.execute(CopperTransactionController.java:54)
	at org.copperengine.core.persistent.txn.CopperTransactionController$1.execute(CopperTransactionController.java:51)
	at org.copperengine.core.db.utility.RetryingTransaction.run(RetryingTransaction.java:128)
	at org.copperengine.core.persistent.txn.CopperTransactionController.run(CopperTransactionController.java:57)
	at org.copperengine.core.persistent.ScottyDBStorage.run(ScottyDBStorage.java:103)
	at org.copperengine.core.persistent.ScottyDBStorage.dequeue(ScottyDBStorage.java:179)
	at org.copperengine.core.persistent.PersistentPriorityProcessorPool.run(PersistentPriorityProcessorPool.java:157)
	at org.copperengine.core.persistent.PersistentPriorityProcessorPool.access$200(PersistentPriorityProcessorPool.java:37)
	at org.copperengine.core.persistent.PersistentPriorityProcessorPool$2.run(PersistentPriorityProcessorPool.java:123)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
I think this was caused by security update in SnakeYaml 2.x.

**Comment by Keymaster65** [comment]
Thank you for your feedback. Was the workflow serialized in 5.4.2 into DB before the upgrade?

**Comment by Keymaster65** [comment]
I was able to reproduce the problem. So I will add a test and fix it.
