### ISSUE TITLE
issue on using FileBasedWorkflowRepository under spring boot multi-module projects

### ISSUE THREAD

**Issue by ArduousBonze** [copper-engine/copper-engine#74]
Hi,

I have a spring boot multi-module projects with `web` and `core`. 
The web module depends on the core module in its pom.xml.  I am using the copper under core module by using  FileBasedWorkflowRepository to locate thew workflow classes. I put all the workflow classer  under path `src\workflow\java` in the core module. 

It's ok when I doing the test on the workflows under core module. But when I run the web module, it reports: 

java.lang.IllegalArgumentException: source directory src/workflow/java does not exist!
	at org.copperengine.core.wfrepo.FileBasedWorkflowRepository.createWfClassMap(FileBasedWorkflowRepository.java:282)
	at org.copperengine.core.wfrepo.FileBasedWorkflowRepository.start(FileBasedWorkflowRepository.java:253)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

How can i fix this exception?  And what's the best practice to use workflow with multi-modules project?  I also noticed that there is ClasspathWorkflowRepository. But I prefer the hot deploy feature supported by FileBasedWorkflowRepository.

Thanks

**Comment by austermann** [comment]
This is no bug, cause the FileBasedWorkflowRepository simply does not find the directory. 

Try the one of the following: 
- use an absolute path 
- change the working dir of your start script to be the one of the "core" 
- mabye another relative path like "../core/src/workflow/java" helps. 




Von: "michael.wc" <notifications@github.com> 
An: "copper-engine/copper-engine" <copper-engine@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Gesendet: Donnerstag, 23. Februar 2017 05:55:36 
Betreff: [copper-engine/copper-engine] issue on using FileBasedWorkflowRepository under spring boot multi-module projects (#74) 



Hi, 

I have a spring boot multi-module projects with web and core . 
The web module depends on the core module in its pom.xml. I am using the copper under core module by using FileBasedWorkflowRepository to locate thew workflow classes. I put all the workflow classer under path src\workflow\java in the core module. 

It's ok when I doing the test on the workflows under core module. But when I run the web project, it reports: 

java.lang.IllegalArgumentException: source directory src/workflow/java does not exist! 
at org.copperengine.core.wfrepo.FileBasedWorkflowRepository.createWfClassMap(FileBasedWorkflowRepository.java:282) 
at org.copperengine.core.wfrepo.FileBasedWorkflowRepository.start(FileBasedWorkflowRepository.java:253) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 

How can i fix this exception? And what's the best practice to use workflow with multi-modules project? I also noticed that these there is ClasspathWorkflowRepository. But I prefer the hot deploy feature supported by FileBasedWorkflowRepository. 

Thanks

**Comment by austermann** [comment]
As stated in my last comment, this is no bug in copper. Issue closed!

**Comment by ArduousBonze** [comment]
Thanks for the help. I finally choose ClasspathWorkflowRepository in my scenario.
