### ISSUE TITLE
Transaction Errors @ Postgres

### ISSUE THREAD

**Issue by rplatzdasch** [copper-engine/copper-engine#98]
Performing multiple wait() call with a time difference smaller than 100ms, crashes transactions.

Oracle 12c with ojdbc8 12.2.0.1 runs stable @ 1ms

Errors occurs on Postgres 10.5-alpine using 9.4-1206-jdbc4

4:51:27 NewPooledConnection:220 WARN  | [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
14:51:27 NewPooledConnection:223 WARN  | [c3p0] Another error has occurred [ org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block ] which will not be reported to listeners!
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:361)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyStatement.java:327)
	at org.copperengine.core.persistent.AbstractSqlDialect.updateQueueState(AbstractSqlDialect.java:379)
	at org.copperengine.core.persistent.ScottyDBStorage$10.run(ScottyDBStorage.java:334)
	at org.copperengine.core.persistent.ScottyDBStorage$10.run(ScottyDBStorage.java:331)
	at org.copperengine.core.persistent.txn.CopperTransactionController$1.execute(CopperTransactionController.java:54)
	at org.copperengine.core.persistent.txn.CopperTransactionController$1.execute(CopperTransactionController.java:51)
	at org.copperengine.core.db.utility.RetryingTransaction.run(RetryingTransaction.java:124)
	at org.copperengine.core.persistent.txn.CopperTransactionController.run(CopperTransactionController.java:51)
	at org.copperengine.core.persistent.ScottyDBStorage.run(ScottyDBStorage.java:99)
	at org.copperengine.core.persistent.ScottyDBStorage.updateQueueState(ScottyDBStorage.java:331)
	at org.copperengine.core.persistent.ScottyDBStorage.access$100(ScottyDBStorage.java:46)
	at org.copperengine.core.persistent.ScottyDBStorage$5.run(ScottyDBStorage.java:229)

**Comment by rplatzdasch** [comment]
Error occurs when using 2 or more engines running parallel

**Comment by rplatzdasch** [comment]
The error prevents workflow instances to be queued. The transcation breaks clean, so the workflow will be queued again. Needs further investigation to see if problem is 100% neglectable.
![error](https://user-images.githubusercontent.com/44027332/49079197-47b9fc80-f240-11e8-85a8-96b03812e4cf.png)
